---

- hosts: localhost
  connection: local
  roles:
    - window-managers
    - kvm
    - docker
    - programming-languages
    - apparmor
    - ufw
    - text-editors
    - jekyll
    - vagrant
    - security
