---

#
# Things that need to be run as root
#

- hosts: localhost
  connection: local
  sudo: True
  roles:
    - browsers
    - window-managers
    - kvm
    - docker
    - programming-languages
    - apparmor
    - ufw
    - text-editors
    - jekyll
    - vagrant
    - security

#
# Things that should be run as the user
#

- hosts: localhost
  connection: local
  sudo: False
  roles:
    - vagrant-plugins
