---

#
# Things that need to be run as root
#

- hosts: localhost
  connection: local
  sudo: True
  roles:
    - browsers
    - window-managers
    - kvm
    - docker
    - programming-languages
    - instant-messaging
    - apparmor
    - ufw
    - text-editors
    - jekyll
    - vagrant
    - virtualbox
    - spideroak
    - ssh
    - security
    - openstack-clients
    - power-management

#
# Things that should be run as the user
#

- hosts: localhost
  connection: local
  sudo: False
  roles:
    - vagrant-plugins
