---

- name: check if vagrant is installed
  shell: which vagrant
  ignore_errors: True
  register: vagrant_installed
  changed_when: False

- debug: msg="ensuring vagrant {{ vagrant_version }} is installed"

- name: download vagrant
  get_url: >
    url=https://dl.bintray.com/mitchellh/vagrant/vagrant_{{ vagrant_version }}_x86_64.deb
    dest=/var/tmp/vagrant.deb
  when: vagrant_installed.rc != 0

- name: install vagrant
  shell: dpkg -i /var/tmp/vagrant.deb
  when: vagrant_installed.rc != 0

- name: ensure /var/tmp/vagrant.deb does not exist
  file: >
    path=/var/tmp/vagrant.deb
    state=absent
