---

- name: check if vagrant is installed
  shell: which vagrant
  ignore_errors: True
  register: vagrant_installed
  changed_when: False

- name: download vagrant
  get_url: >
    url=https://dl.bintray.com/mitchellh/vagrant/vagrant_1.6.5_x86_64.deb
    dest=/var/tmp/vagrant.deb
  when: vagrant_installed.rc != 0

- name: install vagrant
  shell: dpkg -i /var/tmp/vagrant.deb
  when: vagrant_installed.rc != 0

- name: ensure /var/tmp/vagrant.deb does not exist
  file: >
    path=/var/tmp/vagrant.deb
    state=absent

- name: check if vagrant-libvirt plugin is installed
  shell: vagrant plugin list | grep vagrant-libvirt
  register: vagrant_libvirt_plugin
  ignore_errors: True
  changed_when: False

- name: install vagrant-libvirt plugin
  shell: vagrant plugin install vagrant-libvirt
  when: vagrant_libvirt_plugin.rc != 0
