---

- name: ensure ~/.i3 directory exists
  file: >
    path=/home/{{ ansible_env.SUDO_USER }}/.i3
    mode=0755
    state=directory

- name: install i3 config file
  copy: >
    src=i3-config
    dest=/home/{{ ansible_env.SUDO_USER }}/.i3/config
    mode=0644
    owner={{ ansible_env.SUDO_USER }}
    group={{ ansible_env.SUDO_USER }}
